### ISSUE TITLE
WW data download not working

### ISSUE THREAD

**Issue by lgcarmona** [joswr1ght/wwtracked#4]
Hi Josh - 

I'm pretty pissed at Weight Watchers for monetizing by pushing Ozempic, so I wanted to download all of my data (because I am a Virgo and a nerd) before I cancel.

I did capture all of my weights, which was the most important thing to me, but I'd like to try to get my nutrition data. I tried your wwtracked script, which completed successfully, but only gave me headers. The same was true with or without the --nutrition argument:

### Snacks

Any ideas? Do you think they changed the ability to download data?

Thank you!!
LGC

**Comment by joswr1ght** [comment]
I also cancelled my membership, so I don't have the ability to test anymore. 😑 If you want to share a JWT or login creds with me via email (jwright@willhackforsushi.com) I can look at _your data_ to see what's going on, but I don't have another access option.

It's possible they changed the JSON data the API returns which causes the script to be unable to parse the response, but I'm just guessing. Sorry, wish I had a better answer.

**Comment by lgcarmona** [comment]
Hi Josh!Thank you for responding so quickly!Since my WW subscription renews on Dec 6, I don’t want to put that much pressure on you to work on this and get it done in less than a day. I do have my weight data, so I guess the food/nutrition data is just to satisfy my curiosity. It’s ridiculous that WW has gone to drugs when their entire premise was eating healthily. (My doctor said I can’t use Ozempic, so that’s out.)Anyway, thank you for your dedication to open source and quick response!Cheers,LGC*sent from my mobile phoneOn Dec 4, 2023, at 2:59 PM, Joshua Wright ***@***.***> wrote:﻿
I also cancelled my membership, so I don't have the ability to test anymore. 😑 If you want to share a JWT or login creds with me via email ***@***.***) I can look at your data to see what's going on, but I don't have another access option.
It's possible they changed the JSON data the API returns which causes the script to be unable to parse the response, but I'm just guessing. Sorry, wish I had a better answer.
